n = str(input('Digite um numeiro entre 0 e 9999'))
print('Analisando o número {}'.format(n))
print('Unidade:{}'.format(n[3]))
print('Dezena:{}'.format(n[2]))
print('Centena:{}'.format(n[1]))
print('Milhar:{}'.format(n[0]))
